-- MySQL Script generated by MySQL Workbench
-- Fri Jun  5 18:05:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema szpital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema szpital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `szpital` DEFAULT CHARACTER SET utf8 ;
USE `szpital` ;

-- -----------------------------------------------------
-- Table `szpital`.`klient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `szpital`.`klient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `data_ur` DATE NOT NULL,
  `miasto` VARCHAR(45) NOT NULL,
  `adres` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `haslo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szpital`.`zwierze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `szpital`.`zwierze` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  `typ` VARCHAR(45) NOT NULL,
  `rasa` VARCHAR(45) NOT NULL,
  `waga` INT NOT NULL,
  `data` DATE NOT NULL,
  `klient_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_zwierze_klient_idx` (`klient_id` ASC) ,
  CONSTRAINT `fk_zwierze_klient`
    FOREIGN KEY (`klient_id`)
    REFERENCES `szpital`.`klient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szpital`.`asystent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `szpital`.`asystent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `pesel` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `haslo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szpital`.`gabinet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `szpital`.`gabinet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `przeznaczenie` VARCHAR(45) NOT NULL,
  `stoly` INT NOT NULL,
  `opis` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szpital`.`usluga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `szpital`.`usluga` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `typ_uslugi` VARCHAR(45) NOT NULL,
  `cena` DECIMAL(4,2) NOT NULL,
  `asystent_id` INT NOT NULL,
  `gabinet_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wizyta_asystent1_idx` (`asystent_id` ASC) ,
  INDEX `fk_wizyta_gabinet1_idx` (`gabinet_id` ASC) ,
  CONSTRAINT `fk_wizyta_asystent1`
    FOREIGN KEY (`asystent_id`)
    REFERENCES `szpital`.`asystent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wizyta_gabinet1`
    FOREIGN KEY (`gabinet_id`)
    REFERENCES `szpital`.`gabinet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szpital`.`weterynarz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `szpital`.`weterynarz` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `pesel` VARCHAR(45) NOT NULL,
  `specjalizacja` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `haslo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szpital`.`szpital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `szpital`.`szpital` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_przyjecia` DATETIME NOT NULL,
  `data_wyjscia` DATETIME NOT NULL,
  `zwierze_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_szpital_zwierze1_idx` (`zwierze_id` ASC) ,
  CONSTRAINT `fk_szpital_zwierze1`
    FOREIGN KEY (`zwierze_id`)
    REFERENCES `szpital`.`zwierze` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szpital`.`usluga_has_weterynarz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `szpital`.`usluga_has_weterynarz` (
  `usluga_id` INT NOT NULL,
  `weterynarz_id` INT NOT NULL,
  INDEX `fk_usluga_has_weterynarz_weterynarz1_idx` (`weterynarz_id` ASC) ,
  INDEX `fk_usluga_has_weterynarz_usluga1_idx` (`usluga_id` ASC) ,
  CONSTRAINT `fk_usluga_has_weterynarz_usluga1`
    FOREIGN KEY (`usluga_id`)
    REFERENCES `szpital`.`usluga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usluga_has_weterynarz_weterynarz1`
    FOREIGN KEY (`weterynarz_id`)
    REFERENCES `szpital`.`weterynarz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szpital`.`usluga_has_klient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `szpital`.`usluga_has_klient` (
  `usluga_id` INT NOT NULL,
  `klient_id` INT NOT NULL,
  INDEX `fk_usluga_has_klient_klient1_idx` (`klient_id` ASC) ,
  INDEX `fk_usluga_has_klient_usluga1_idx` (`usluga_id` ASC) ,
  CONSTRAINT `fk_usluga_has_klient_usluga1`
    FOREIGN KEY (`usluga_id`)
    REFERENCES `szpital`.`usluga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usluga_has_klient_klient1`
    FOREIGN KEY (`klient_id`)
    REFERENCES `szpital`.`klient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szpital`.`usluga_has_zwierze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `szpital`.`usluga_has_zwierze` (
  `usluga_id` INT NULL,
  `zwierze_id` INT NULL,
  INDEX `fk_usluga_has_zwierze_zwierze1_idx` (`zwierze_id` ASC) ,
  INDEX `fk_usluga_has_zwierze_usluga1_idx` (`usluga_id` ASC) ,
  CONSTRAINT `fk_usluga_has_zwierze_usluga1`
    FOREIGN KEY (`usluga_id`)
    REFERENCES `szpital`.`usluga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usluga_has_zwierze_zwierze1`
    FOREIGN KEY (`zwierze_id`)
    REFERENCES `szpital`.`zwierze` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `szpital`.`klient`
-- -----------------------------------------------------
START TRANSACTION;
USE `szpital`;
INSERT INTO `szpital`.`klient` (`id`, `imie`, `nazwisko`, `email`, `data_ur`, `miasto`, `adres`, `login`, `haslo`) VALUES (1, 'admin', 'adminowski', 'admin@wp.pl', DEFAULT, DEFAULT, DEFAULT, 'admin', '123');

COMMIT;


-- -----------------------------------------------------
-- Data for table `szpital`.`zwierze`
-- -----------------------------------------------------
START TRANSACTION;
USE `szpital`;
INSERT INTO `szpital`.`zwierze` (`id`, `imie`, `typ`, `rasa`, `waga`, `data`, `klient_id`) VALUES (1, 'sz', 'kot', 'kundel', 12, DEFAULT, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `szpital`.`asystent`
-- -----------------------------------------------------
START TRANSACTION;
USE `szpital`;
INSERT INTO `szpital`.`asystent` (`id`, `imie`, `nazwisko`, `pesel`, `login`, `haslo`) VALUES (1, 'Dorota', 'Ruśnik', '980967212', 'Dorotar', 'dorota123');

COMMIT;


-- -----------------------------------------------------
-- Data for table `szpital`.`gabinet`
-- -----------------------------------------------------
START TRANSACTION;
USE `szpital`;
INSERT INTO `szpital`.`gabinet` (`id`, `przeznaczenie`, `stoly`, `opis`) VALUES (1, 'ogolny', 2, 'ogolny');

COMMIT;


-- -----------------------------------------------------
-- Data for table `szpital`.`usluga`
-- -----------------------------------------------------
START TRANSACTION;
USE `szpital`;
INSERT INTO `szpital`.`usluga` (`id`, `typ_uslugi`, `cena`, `asystent_id`, `gabinet_id`) VALUES (1, 'szczepienie', 60, 1, 1);
INSERT INTO `szpital`.`usluga` (`id`, `typ_uslugi`, `cena`, `asystent_id`, `gabinet_id`) VALUES (2, 'badanie', 40, 1, 1);
INSERT INTO `szpital`.`usluga` (`id`, `typ_uslugi`, `cena`, `asystent_id`, `gabinet_id`) VALUES (3, 'odrobaczanie', 20, 1, 1);
INSERT INTO `szpital`.`usluga` (`id`, `typ_uslugi`, `cena`, `asystent_id`, `gabinet_id`) VALUES (4, 'sterylizacja', 100, 1, 1);
INSERT INTO `szpital`.`usluga` (`id`, `typ_uslugi`, `cena`, `asystent_id`, `gabinet_id`) VALUES (5, 'pchly', 30, 1, 1);
INSERT INTO `szpital`.`usluga` (`id`, `typ_uslugi`, `cena`, `asystent_id`, `gabinet_id`) VALUES (6, 'konsultacjazvet', 40, 1, 1);
INSERT INTO `szpital`.`usluga` (`id`, `typ_uslugi`, `cena`, `asystent_id`, `gabinet_id`) VALUES (7, 'chipowanie', 45, 1, 1);
INSERT INTO `szpital`.`usluga` (`id`, `typ_uslugi`, `cena`, `asystent_id`, `gabinet_id`) VALUES (8, 'stomatolog', 35, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `szpital`.`weterynarz`
-- -----------------------------------------------------
START TRANSACTION;
USE `szpital`;
INSERT INTO `szpital`.`weterynarz` (`id`, `imie`, `nazwisko`, `pesel`, `specjalizacja`, `login`, `haslo`) VALUES (1, 'Tomasz', 'Barszczynski', '9709190743', 'Weterynarz', 'Barszczynski', 'barszczyk123');

COMMIT;

